import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import { Lora } from 'next/font/google'

const fontFace = Lora({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-lora',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontFace.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
